export const errorCodes = {
  1000: 'Unknown error',
  1001: 'Order ids list length is not equal to sport ids list',
  1002: "Widget doesn't contain details",
  1003: 'Bet is already settled',
  1004: 'The value field is missing',
  1005: 'Cannot find banner component, skip adding',
  1006: 'Cannot find sports widget component, skip adding',
  1007: 'Cannot find racing widget component, skip adding',
  1008: 'Racing widget showing is turned off',
  1009: 'Cannot find sport provider',
  1010: 'No market ids found for sport',
  1011: 'No data found for sport',
  1012: 'Authorize first',
  1013: 'The game is already favorite',
  1014: 'The game is not favorite',
  1015: 'Sport content data not found',
  1016: 'Provide pragmatic or regular game id',
  1017: 'Page content not found',
  1018: 'Banner date is restricted',
  1019: 'Sport widget date is restricted',
  1020: 'Global SEO does not exist',
  1021: 'Some company settings does not exist',
  1022: 'Race card data does not exist',
  1023: 'Css style does not exist',
  1024: 'Terms and conditions does not exist',
  1025: 'Privacy policy does not exist',
  1026: 'Casino category does not exist',
  1027: 'No events found for racing widget with hide if no events = true',
  1028: 'Event not found',
  1029: 'The event is no longer available',
  1030: 'Bet ticker id is not found',
  1031: 'Please provide bet ticker id',
  1032: 'Access denied: You do not have permission to access this resource',
  1033: 'Wrong event provider',
  1034: 'Provide affiliate slug',
  1035: 'Landing page is not found',
  1036: 'JWT token has expired',
  1037: 'Banner game not found banned for current country',
  1038: 'Component is not found',
  1039: 'Casino games not found or banned for current country',
  1040: 'Sport name not found',
  1041: 'No markets list associated with current sport or event',
  1042: 'Event is no longer displayable',
  1043: 'User not found',
  1044: 'Sport is disabled',
  1045: 'Device ID is missing',
  1046: 'Password need to be changed',
  1048: 'Email or password is incorrect',
  1049: 'Country is not valid',
  1050: 'KYC is not verified',
  1051: 'You first need to set the deposit limit',
  1052: 'Phone number is not verified',
  1053: 'The phone number must be the same with the country prefix',
  1054: 'The phone number must be set',
  1055: 'E-mail is not verified',
  1056: 'You have reached the daily deposit limit',
  1057: 'You have reached the weekly deposit limit',
  1058: 'You have reached the monthly deposit limit',
  1059: 'Amount is not valid',
  1060: 'Your profile is excluded until {{excluded_until}}',
  1061: 'Your account is blocked for 10 minutes, please try again later',
  1063: 'FCM token is missing',
  1064: 'Error in SQL, check the logs for more details',
  1065: 'City is missing',
  1066: 'Zip code is missing',
  1067: 'Country is missing',
  1068: 'Address is missing',
  1069: 'Phone number is missing',
  1070: 'Phone prefix is missing',
  1071: 'You hit the max. deposit limit per transaction',
  1072: 'You reached deposit limits',
  1073: 'Country of prefix is not valid',
  1074: 'The balance is insufficient',
  1075: 'Name is missing',
  1076: 'E-mail is missing',
  1077: 'E-mail is invalid',
  1078: 'Account is suspended, please contact support',
  1079: 'No active free bets',
  1080: 'Accept the new odds',
  1081: 'Selection is suspended',
  1082: 'No default market set for this sport',
  1083: 'Selection has been suspended',
  1084: 'Insufficient balance',
  1085: 'Event has started',
  1086: 'Error in adding single bet',
  1087: 'Error in adding user bet',
  1088: 'Error in adding transaction',
  1089: 'Error in adding multiple bet',
  1090: 'Please sign in',
  1091: 'User is not allowed to play a casino game',
  1092: 'Refresh Token has expired',
  1093: 'Intentional promise rejection',
  1094: 'Competition is not found',
  1095: 'Invalid JWT token',
  1096: 'Google place details not found',
  1097: 'Date of birth is missing',
  1098: 'Country is restricted for casino games',
  1099: 'Sport does not have any events',
  1100: 'Missing SIS_CUSTOMER_HASH or SIS_SECRET_KEY in environment variables in the SisStreamService',
  1101: 'Failed to get streaming events',
  1102: 'Failed to get stream url',
  1103: 'Balance deposit is required to watch the stream',
  1104: 'Maximum of 25 selections allowed',
  1105: 'Invalid format',
  1106: 'OTP verification attempts limit exceeded, please try again in 5 minutes.',
  1107: 'Invalid OTP code',
  1108: 'OTP code has expired, please try to login again',
  1109: 'Email is already verified, please try to login again',
  1110: 'Please contact support, your account has an issue with KYC',
  1111: 'Sport does not have a competitions',
  1112: 'Recovery link is expired',
  1113: 'Password should contain at least 8 characters, one lowercase letter, one number and one special character',
  1114: 'Incorrect old password',
  1115: 'Value is not valid',
  1116: 'Selection is not found',
  1117: 'Action has been already confirmed',
  1118: 'Account is pending, please contact support',
  1119: 'This phone number is already in use',
  1120: 'First name is invalid',
  1121: 'Last name is invalid',
  1122: 'Country code is invalid',
  1123: 'Date of birth is invalid',
  1124: 'State is invalid',
  1125: 'You are not eligible to gamble due to age restrictions in your country.',
  1126: 'E-mail is already in use',
  1127: 'Invalid Password',
  1128: 'Password is to long',
  1129: 'Competition does not have an events',
  1130: 'Account is closed, please contact support',
  1131: 'Account is pending, please contact support',
  1132: 'The maximum deposit amount allowed without KYC is {{amount}} {{currency}}.\n So far, you have deposited {{deposited_amount}} {{currency}}.',
  1133: 'Refresh Token is missing',
  1134: 'Phone number cannot be changed without phone verification',
  1135: 'Your account is locked, please contact support',
  1136: 'Country restricted',
  1137: 'There is a daily system limit of {{amount}}. Please select a value less then this amount.',
  1138: 'There is a weekly system limit of {{amount}}. Please select a value less then this amount.',
  1139: 'There is a monthly system limit of {{amount}}. Please select a value less then this amount.',
  1140: 'National ID Number is missing',
  1141: 'National ID Number is invalid',
  1142: 'Reset password link has expired, please try to reset password again',
  1143: 'Captcha verification failed',
  1144: 'Your self exclusion period has finished, please contact customer support',
  1145: 'Compliance ticker not found',
  1146: 'Compliance questionnaire answers amount are not equal to questions amount',
  1147: "Compliance doesn't have questions",
  1148: 'Compliance item not found',
  1149: 'Min. withdrawal amount is {{amount}} {{currency}}',
  1150: 'GamStop has not been checked or the check is older than 24 hours.',
  1151: 'Competition {{name}} is not available',
  1152: 'Deposits have been disabled on your account. Please contact support for more info.',
  1153: 'Net Daily Limit reached',
  1154: 'Net Weekly Limit reached',
  1155: 'Net Monthly Limit reached',
  1156: 'SMS phone verification failed',
  1157: 'Phone Number is incorrect',
  1158: 'Token is blacklisted',
  1159: 'Max withdrawal limit has been reached for today.',
  1160: 'Promo offer not found',
  1161: 'Source of funds type is missing',
  1162: 'Provider id is missing',
  1163: 'Invalid city format',
  1164: 'Invalid address format',
  1165: 'Invalid state format',
  1166: 'Invalid house number format',
  1167: 'Wrong email format',
  1168: 'Invalid zip code format',
  1169: 'Bet builder is not enabled',
  1170: 'Reset link missing',
  1171: 'Provider id is missing',
  1172: 'This email address has been restricted from creating an account.',
  1173: 'Password cannot contain your email username',
  1174: 'Refresh Token is invalid',
  1175: 'Please contact administrator.',
  1176: 'You already have a bet under review. Please wait until its completed before submitting another.',
  1177: 'Popup type not found',
  1178: 'Preferences are missing',
  1179: 'Enable/disable values should be 0 or 1',
  1181: 'Necessary cookies cannot be disabled',
  1182: 'Wagering is disabled on your account. Please contact support.',
  1183: 'The cookie type id is invalid',
};
