export const excludedVenues = new Set([
  'Aintree',
  'Ascot',
  'Ayr',
  'Bellewstown',
  'Ballinrobe',
  'Catterick',
  'Chelmsford',
  'Cheltenham',
  'Curragh',
  'Carlisle',
  'Clonmel',
  'Cork',
  'Durbanville',
  'Dundalk',
  'Down Royal',
  'Downpatrick',
  'Exeter',
  'Fairyhouse',
  'Fakenham',
  'Galway',
  'Gowran Park',
  'Huntingdon',
  'Kelso',
  'Kempton',
  'Killarney',
  'Kilbeggan',
  'Leicester',
  'Ludlow',
  'Leopardstown',
  'Limerick',
  'Market Rasen',
  'Musselburgh',
  'Naas',
  'Navan',
  'Newbury',
  'Punchestown',
  'Taunton',
  'Tipperary',
  'Thurles',
  'Tramore',
  'Sandown',
  'Warwick',
  'Wexford',
  'Wetherby',
  'Wincanton',
  'Vaal',
]);
